import type { ExtractPropTypes, PropType } from 'vue'
import type { FormRules, Arrayable, FormItemRule } from './interface'

export type FormLayout = 'horizontal' | 'vertical' | 'inline'
export type FormLabelAlign = 'left' | 'right' | 'top'
export type FormSize = 'mini' | 'small' | 'medium' | 'large'

export const formProps = {
  /**
   * 表单数据对象
   * @en Form data object
   */
  model: {
    type: Object as PropType<Record<string, any>>,
  },
  /**
   * 表单验证规则
   * @en Form validation rules
   */
  rules: {
    type: Object as PropType<FormRules>,
  },
  /**
   * 表单布局
   * @en Form layout
   */
  layout: {
    type: String as PropType<FormLayout>,
    default: 'vertical',
  },
  /**
   * 标签对齐方式
   * @en Label alignment
   */
  labelAlign: {
    type: String as PropType<FormLabelAlign>,
    default: 'right',
  },
  /**
   * 标签宽度，支持数字（像素）或字符串（如 '100px', '20%'）
   * @en Label width, supports number (pixels) or string (e.g. '100px', '20%')
   */
  labelWidth: {
    type: [String, Number] as PropType<string | number>,
    default: '',
  },
  /**
   * 表单尺寸，如果不设置则使用组件库默认尺寸
   * @en Form size, uses component library default size if not set
   */
  size: {
    type: String as PropType<FormSize>,
  },
  /**
   * 是否禁用该表单内的所有组件
   * @en Whether to disable all components in this form
   */
  disabled: {
    type: Boolean,
    default: false,
  },
  /**
   * 是否隐藏必填字段的标签旁边的红色星号
   * @en Whether to hide the red asterisk next to the label of required fields
   */
  hideRequiredAsterisk: {
    type: Boolean,
    default: false,
  },
  /**
   * 表单校验失败时，是否滚动到第一个错误表单项
   * @en Whether to scroll to the first error form item when form validation fails
   */
  scrollToError: {
    type: Boolean,
    default: false,
  },
  /**
   * 是否显示校验错误信息
   * @en Whether to show the validation error message
   */
  showMessage: {
    type: Boolean,
    default: true,
  }
} as const

export const formEmits = {
  /**
   * 任一表单项被校验后触发
   * @en Triggered after any form item is validated
   */
  validate: (prop: string, isValid: boolean, message: string) => true,
}

export const formSlots = {
  /**
   * 表单内容
   * @en Form content
   */
  default: (_: {}) => true,
}

export type FormProps = ExtractPropTypes<typeof formProps> 

export const formItemProps = {
  /**
   * model 的键名。它可以是一个路径数组(例如 ['a', 'b', 0])。在定义了 validate、resetFields 的方法时，该属性是必填的
   * @en A field name of the model. It could be an array of paths (e.g. ['a', 'b', 0]). In the definition of validate and resetFields method, the attribute is required
   */
  prop: String,
  /**
   * 标签文本
   * @en Label text
   */
  label: String,
  /**
   * 标签宽度，例如 '50px'。支持 auto。
   * @en Label width, e.g. '50px'. Supports auto.
   */
  labelWidth: [String, Number] as PropType<string | number>,
  /**
   * 是否必填，如不设置，则会根据校验规则自动生成
   * @en Whether the field is required or not, will be generated by validation rules if not set
   */
  required: {
    type: Boolean,
    default: undefined,
  },
  /**
   * 表单验证规则
   * @en Form validation rules
   */
  rules: [Object, Array] as PropType<Arrayable<FormItemRule>>, 
  /**
   * 表单域验证错误信息, 设置该值会使表单验证状态变为 error，并显示该错误信息
   * @en Form field validation error message, setting this value will change the form validation state to error and show this error message
   */
  error: String,
  /**
   * 表单域验证状态
   * @en Form field validation state
   */
  validateStatus: String,
  /**
   * 指定原生的 label 标签的 for 属性
   * @en Specify the for attribute of the native label tag
   */
  for: String,
  /**
   * 是否显示校验错误信息
   * @en Whether to show the validation error message
   */
  showMessage: {
    type: Boolean,
    default: true,
  }
} as const

export const formItemEmits = {}

export const formItemSlots = {
  /**
   * 表单项内容
   * @en Form Item content
   */
  default: (_: {}) => true,
  /**
   * 标签文本的内容
   * @en Label content
   */
  label: (_: { label: string }) => true,
  /**
   * 验证错误信息的自定义内容
   * @en Custom content for validation error message
   */
  error: (_: { error: string }) => true,
}

export type FormItemProps = ExtractPropTypes<typeof formItemProps>
