// 由 scripts/sync-sfc-playground-runtime.mjs 自动生成
// 请勿手动修改

export const playgroundStyleManifest = [
  "amu-ui/assets/components/breadcrumb/src/style.css",
  "amu-ui/assets/components/button/src/style.css",
  "amu-ui/assets/components/card/src/style.css",
  "amu-ui/assets/components/cascader/src/style.css",
  "amu-ui/assets/components/checkbox/src/checkbox-group.css",
  "amu-ui/assets/components/checkbox/src/checkbox.css",
  "amu-ui/assets/components/col/src/style.css",
  "amu-ui/assets/components/collapse/src/style.css",
  "amu-ui/assets/components/date-picker/src/style.css",
  "amu-ui/assets/components/descriptions/src/style.css",
  "amu-ui/assets/components/dialog/src/dialog.css",
  "amu-ui/assets/components/drawer/src/drawer.css",
  "amu-ui/assets/components/dropdown/src/style.css",
  "amu-ui/assets/components/empty/src/style.css",
  "amu-ui/assets/components/form/src/style.css",
  "amu-ui/assets/components/icon/src/style.css",
  "amu-ui/assets/components/image-viewer/src/image-viewer.css",
  "amu-ui/assets/components/image-viewer/src/style.css",
  "amu-ui/assets/components/input-number/src/style.css",
  "amu-ui/assets/components/input/src/style.css",
  "amu-ui/assets/components/layout/src/style.css",
  "amu-ui/assets/components/loading/src/style.css",
  "amu-ui/assets/components/menu/src/style.css",
  "amu-ui/assets/components/menu/src/sub-menu.css",
  "amu-ui/assets/components/message/src/style.css",
  "amu-ui/assets/components/pagination/src/style.css",
  "amu-ui/assets/components/popconfirm/src/popconfirm.css",
  "amu-ui/assets/components/popconfirm/src/style.css",
  "amu-ui/assets/components/popup/src/popup.css",
  "amu-ui/assets/components/progress/src/style.css",
  "amu-ui/assets/components/radio/src/style.css",
  "amu-ui/assets/components/rate/src/style.css",
  "amu-ui/assets/components/row/src/style.css",
  "amu-ui/assets/components/scrollbar/src/style.css",
  "amu-ui/assets/components/select/src/style.css",
  "amu-ui/assets/components/skeleton/src/style.css",
  "amu-ui/assets/components/slider/src/style.css",
  "amu-ui/assets/components/space/src/style.css",
  "amu-ui/assets/components/spinner/src/style.css",
  "amu-ui/assets/components/swiper/src/style.css",
  "amu-ui/assets/components/switch/src/style.css",
  "amu-ui/assets/components/table/src/components/filter-panel.css",
  "amu-ui/assets/components/table/src/components/virtual-scroller.css",
  "amu-ui/assets/components/table/src/table.css",
  "amu-ui/assets/components/tabs/src/style.css",
  "amu-ui/assets/components/tag/src/style.css",
  "amu-ui/assets/components/textarea/src/style.css",
  "amu-ui/assets/components/tooltip/src/style.css",
  "amu-ui/assets/components/tree/src/style.css",
  "amu-ui/assets/components/upload/src/style.css",
  "amu-ui/assets/theme/src/index.css",
] as const
